//! Sessions, checkpoints, and commit logic.
//!
//! A checkpoint is an immutable snapshot of a coherent graph state.
//! A session is the working interval between two checkpoints: it maintains
//! a mutable projection of the base graph, records all mutations in a patch,
//! and tracks obligations generated by entry-content changes.
//!
//! The agent drives the obligation discharge loop. The session provides
//! state (working graph, pending obligations, visited entries) and operations
//! (mutate, confirm, resolve, justify, approve, commit). The agent decides
//! traversal order.

use std::collections::HashSet;

use crate::entry::EntryId;
use crate::graph::{Graph, GraphError};
use crate::mutation::{FieldUpdate, Mutation, Patch};
use crate::obligation::{Justification, ObligationId, ObligationSet, ObligationStatus};

/// Immutable snapshot of the graph at a moment of coherence.
///
/// Every checkpoint satisfies the coherence invariant: all obligations
/// discharged and all groundings accurate.
#[derive(Clone, Debug)]
pub struct Checkpoint {
    /// The graph state at the time of the snapshot.
    graph: Graph,
}

impl Checkpoint {
    /// Create a checkpoint from a graph that is assumed coherent.
    ///
    /// Note: coherence is not verified at construction. The caller is
    /// responsible for ensuring all obligations are discharged.
    pub fn new(graph: Graph) -> Self {
        Self { graph }
    }

    /// The graph at the time of the snapshot.
    pub fn graph(&self) -> &Graph {
        &self.graph
    }
}

/// Errors arising from session operations.
#[derive(Debug, thiserror::Error)]
pub enum SessionError {
    #[error(transparent)]
    Graph(#[from] GraphError),

    #[error("entry is locked: {0}")]
    EntryLocked(EntryId),

    #[error("obligation not found: {0}")]
    ObligationNotFound(ObligationId),

    #[error("obligation is not pending: {0}")]
    ObligationNotPending(ObligationId),

    #[error("obligation is not awaiting approval: {0}")]
    ObligationNotAwaitingApproval(ObligationId),

    #[error("cannot commit: unresolved obligations remain")]
    ObligationsIncomplete,

    #[error("cannot commit: pending approvals remain")]
    ApprovalsIncomplete,
}

/// Working interval between two checkpoints.
///
/// All mutations during a working interval flow through the session, which
/// maintains a working copy of the graph (base + applied mutations), records
/// mutations in a patch, and generates obligations from dependency edges when
/// entry content changes.
///
/// The agent drives the obligation discharge iteration: it queries pending
/// obligations, picks which to examine, and calls the appropriate discharge
/// method. The session tracks visited entries for cycle detection but does
/// not impose traversal order.
#[derive(Clone, Debug)]
pub struct Session {
    /// The frozen base checkpoint.
    base: Checkpoint,
    /// Working graph state: base graph with all mutations applied.
    working: Graph,
    /// Accumulated mutations since the base.
    patch: Patch,
    /// Outstanding proof burdens.
    obligations: ObligationSet,
    /// Entries examined during obligation discharge. Helps the agent
    /// detect cycle re-entry.
    visited: HashSet<EntryId>,
}

impl Session {
    /// Start a new session from a checkpoint.
    ///
    /// Clones the base graph into a working copy. The patch, obligations,
    /// and visited set start empty.
    pub fn new(base: Checkpoint) -> Self {
        let working = base.graph.clone();
        Self {
            base,
            working,
            patch: Patch::new(),
            obligations: ObligationSet::new(),
            visited: HashSet::new(),
        }
    }

    // -- read accessors ------------------------------------------------------

    /// The frozen base checkpoint.
    pub fn base(&self) -> &Checkpoint {
        &self.base
    }

    /// The current working graph state (base + all applied mutations).
    pub fn graph(&self) -> &Graph {
        &self.working
    }

    /// The accumulated patch.
    pub fn patch(&self) -> &Patch {
        &self.patch
    }

    /// The obligation set.
    pub fn obligations(&self) -> &ObligationSet {
        &self.obligations
    }

    /// Whether an entry has been examined during obligation discharge.
    pub fn is_visited(&self, id: &EntryId) -> bool {
        self.visited.contains(id)
    }

    // -- mutation ------------------------------------------------------------

    /// Apply a mutation to the working graph.
    ///
    /// Records the mutation in the patch. For entry-content mutations
    /// (`UpdateEntry`, `RemoveEntry`), generates obligations on all
    /// dependent entries. Fails if the mutation targets a locked entry.
    pub fn mutate(&mut self, mutation: Mutation) -> Result<(), SessionError> {
        // Check lock constraint for entry-content mutations.
        match &mutation {
            | Mutation::UpdateEntry { id, .. } | Mutation::RemoveEntry(id) => {
                if self.working.is_locked(id) {
                    return Err(SessionError::EntryLocked(id.clone()));
                }
            }
            | _ => {}
        }
        self.apply_and_propagate(mutation)
    }

    // -- obligation discharge ------------------------------------------------

    /// Confirm the obligation's target is still valid.
    ///
    /// Marks the obligation as discharged and adds the target to the
    /// visited set.
    pub fn confirm(&mut self, id: ObligationId) -> Result<(), SessionError> {
        let obligation = self
            .obligations
            .get(&id)
            .ok_or_else(|| SessionError::ObligationNotFound(id.clone()))?;
        if !matches!(obligation.status(), ObligationStatus::Pending) {
            return Err(SessionError::ObligationNotPending(id));
        }
        let target = obligation.target().clone();
        self.visited.insert(target);
        self.obligations.get_mut(&id).unwrap().set_status(ObligationStatus::Discharged);
        Ok(())
    }

    /// Discharge an obligation by updating the target entry.
    ///
    /// Applies the update through the normal `mutate()` path, which may
    /// generate further obligations on dependents. If the target entry is
    /// locked, `mutate()` returns `EntryLocked` — the agent should use
    /// `justify()` instead.
    pub fn resolve(&mut self, id: ObligationId, update: Mutation) -> Result<(), SessionError> {
        let obligation = self
            .obligations
            .get(&id)
            .ok_or_else(|| SessionError::ObligationNotFound(id.clone()))?;
        if !matches!(obligation.status(), ObligationStatus::Pending) {
            return Err(SessionError::ObligationNotPending(id));
        }
        let target = obligation.target().clone();
        self.mutate(update)?;
        self.visited.insert(target);
        self.obligations.get_mut(&id).unwrap().set_status(ObligationStatus::Discharged);
        Ok(())
    }

    /// Submit a justification for a locked entry's obligation.
    ///
    /// The obligation remains pending (as `AwaitingApproval`) until a
    /// reviewer calls `approve()`.
    pub fn justify(
        &mut self, id: ObligationId, argument: String, mutation: Mutation,
    ) -> Result<(), SessionError> {
        let obligation = self
            .obligations
            .get(&id)
            .ok_or_else(|| SessionError::ObligationNotFound(id.clone()))?;
        if !matches!(obligation.status(), ObligationStatus::Pending) {
            return Err(SessionError::ObligationNotPending(id));
        }
        let entry = obligation.target().clone();
        let justification = Justification { entry, mutation: Box::new(mutation), argument };
        self.obligations
            .get_mut(&id)
            .unwrap()
            .set_status(ObligationStatus::AwaitingApproval(justification));
        Ok(())
    }

    /// Approve a pending justification (external reviewer action).
    ///
    /// Applies the deferred mutation directly — the approval is the
    /// authorization, so the lock is not rechecked. Generates further
    /// obligations on dependents and adds the target to the visited set.
    pub fn approve(&mut self, id: ObligationId) -> Result<(), SessionError> {
        let obligation = self
            .obligations
            .get(&id)
            .ok_or_else(|| SessionError::ObligationNotFound(id.clone()))?;
        let justification = match obligation.status() {
            | ObligationStatus::AwaitingApproval(j) => j.clone(),
            | _ => return Err(SessionError::ObligationNotAwaitingApproval(id)),
        };
        let target = obligation.target().clone();
        // Apply the deferred mutation, bypassing lock check.
        self.apply_and_propagate(*justification.mutation)?;
        self.visited.insert(target);
        self.obligations.get_mut(&id).unwrap().set_status(ObligationStatus::Discharged);
        Ok(())
    }

    // -- commit --------------------------------------------------------------

    /// Promote the patch to a new checkpoint. Consumes the session.
    ///
    /// Requires both obligation-completeness (all discharged) and
    /// approval-completeness (no pending approvals).
    pub fn commit(self) -> Result<Checkpoint, SessionError> {
        if self.obligations.has_pending_approvals() {
            return Err(SessionError::ApprovalsIncomplete);
        }
        if !self.obligations.is_complete() {
            return Err(SessionError::ObligationsIncomplete);
        }
        Ok(Checkpoint::new(self.working))
    }

    // -- internal ------------------------------------------------------------

    /// Apply a mutation to the working graph, record it in the patch,
    /// and generate obligations on dependents for entry-content mutations.
    ///
    /// Does not check locks. Callers are responsible for lock enforcement.
    fn apply_and_propagate(&mut self, mutation: Mutation) -> Result<(), SessionError> {
        // Capture the cause entry and its dependents before applying.
        // RemoveEntry deletes edges, so dependents must be captured first.
        let cause_and_dependents: Option<(EntryId, Vec<EntryId>)> = match &mutation {
            | Mutation::UpdateEntry { id, .. } | Mutation::RemoveEntry(id) => {
                let dependents: Vec<EntryId> = self.working.dependents_of(id).cloned().collect();
                Some((id.clone(), dependents))
            }
            | _ => None,
        };

        // Apply mutation to the working graph.
        Self::apply_to_graph(&mut self.working, &mutation)?;

        // Record in the patch.
        self.patch.push(mutation);

        // Generate obligations on dependents.
        if let Some((cause, dependents)) = cause_and_dependents {
            for dependent in dependents {
                self.obligations.generate(dependent, cause.clone());
            }
        }

        Ok(())
    }

    /// Apply a single mutation to a graph.
    fn apply_to_graph(graph: &mut Graph, mutation: &Mutation) -> Result<(), GraphError> {
        match mutation {
            | Mutation::CreateEntry(entry) => {
                graph.insert_entry(entry.clone())?;
            }
            | Mutation::RemoveEntry(id) => {
                graph.remove_entry(id).ok_or_else(|| GraphError::EntryNotFound(id.clone()))?;
            }
            | Mutation::UpdateEntry { id, name, description, explanation } => {
                let entry =
                    graph.entry_mut(id).ok_or_else(|| GraphError::EntryNotFound(id.clone()))?;
                match name {
                    | FieldUpdate::Set(n) => entry.set_name(Some(n.clone())),
                    | FieldUpdate::Clear => entry.set_name(None),
                    | FieldUpdate::Unchanged => {}
                }
                match description {
                    | FieldUpdate::Set(d) => entry.set_description(d.clone()),
                    // Note: description is a required field; Clear is a no-op.
                    | FieldUpdate::Clear | FieldUpdate::Unchanged => {}
                }
                match explanation {
                    | FieldUpdate::Set(e) => entry.set_explanation(e.clone()),
                    // Note: explanation is a required field; Clear is a no-op.
                    | FieldUpdate::Clear | FieldUpdate::Unchanged => {}
                }
            }
            | Mutation::AddDependency(dep) => {
                graph.add_dependency(dep.clone())?;
            }
            | Mutation::RemoveDependency(dep) => {
                graph.remove_dependency(dep);
            }
            | Mutation::AddAffinity(aff) => {
                graph.add_affinity(aff.clone());
            }
            | Mutation::RemoveAffinity(aff) => {
                graph.remove_affinity(aff);
            }
            | Mutation::AddGrounding { entry, grounding } => {
                graph.add_grounding(entry, grounding.clone())?;
            }
            | Mutation::Lock(id) => {
                graph.lock(id)?;
            }
            | Mutation::Unlock(id) => {
                graph.unlock(id);
            }
        }
        Ok(())
    }
}
