//! Sessions, checkpoints, and commit logic.
//!
//! A checkpoint is an immutable snapshot of a coherent graph state.
//! A session is the working interval between two checkpoints: it maintains
//! a mutable projection of the base graph, records all mutations in a patch,
//! and tracks obligations generated by entry-content changes.
//!
//! The agent drives the obligation discharge loop. The session provides
//! state (working graph, pending obligations, visited entries) and operations
//! (mutate, confirm, resolve, justify, approve, commit). The agent decides
//! traversal order.

use std::collections::HashSet;

use crate::entry::EntryId;
use crate::graph::{Graph, GraphError};
use crate::grounding::{GroundingFailure, GroundingValidator};
use crate::mutation::{FieldUpdate, Mutation, Patch};
use crate::obligation::{Justification, ObligationId, ObligationSet, ObligationStatus};
use tracing::debug;

/// Immutable snapshot of the graph at a moment of coherence.
///
/// Every checkpoint satisfies the coherence invariant: all obligations
/// discharged, all locked-entry mutations approved, and all groundings
/// validated under the commit-time grounding validator.
#[derive(Clone, Debug)]
pub struct Checkpoint {
    /// The graph state at the time of the snapshot.
    graph: Graph,
}

impl Checkpoint {
    /// Create a checkpoint from a graph that is assumed coherent.
    ///
    /// Note: coherence is not verified at construction. `Session::commit()`
    /// is the checked entry point.
    pub fn new(graph: Graph) -> Self {
        Self { graph }
    }

    /// The graph at the time of the snapshot.
    pub fn graph(&self) -> &Graph {
        &self.graph
    }
}

/// Errors arising from session operations.
#[derive(Debug, thiserror::Error)]
pub enum SessionError {
    #[error(transparent)]
    Graph(#[from] GraphError),

    #[error("entry is locked: {0}")]
    EntryLocked(EntryId),

    #[error("obligation not found: {0}")]
    ObligationNotFound(ObligationId),

    #[error("obligation is not pending: {0}")]
    ObligationNotPending(ObligationId),

    #[error("obligation is not awaiting approval: {0}")]
    ObligationNotAwaitingApproval(ObligationId),

    #[error("cannot commit: unresolved obligations remain")]
    ObligationsIncomplete,

    #[error("cannot commit: pending approvals remain")]
    ApprovalsIncomplete,

    #[error(transparent)]
    GroundingInvalid(#[from] GroundingFailure),
}

/// Working interval between two checkpoints.
///
/// All mutations during a working interval flow through the session, which
/// maintains a working copy of the graph (base + applied mutations), records
/// mutations in a patch, and generates obligations from dependency edges when
/// entry content changes.
///
/// The agent drives the obligation discharge iteration: it queries pending
/// obligations, picks which to examine, and calls the appropriate discharge
/// method. The session tracks visited entries for cycle detection but does
/// not impose traversal order.
#[derive(Clone, Debug)]
pub struct Session {
    /// The frozen base checkpoint.
    base: Checkpoint,
    /// Working graph state: base graph with all mutations applied.
    working: Graph,
    /// Accumulated mutations since the base.
    patch: Patch,
    /// Outstanding proof burdens.
    obligations: ObligationSet,
    /// Entries examined during obligation discharge. Helps the agent
    /// detect cycle re-entry.
    visited: HashSet<EntryId>,
}

impl Session {
    /// Start a new session from a checkpoint.
    ///
    /// Clones the base graph into a working copy. The patch, obligations,
    /// and visited set start empty.
    pub fn new(base: Checkpoint) -> Self {
        let working = base.graph.clone();
        Self {
            base,
            working,
            patch: Patch::new(),
            obligations: ObligationSet::new(),
            visited: HashSet::new(),
        }
    }

    // -- read accessors ------------------------------------------------------

    /// The frozen base checkpoint.
    pub fn base(&self) -> &Checkpoint {
        &self.base
    }

    /// The current working graph state (base + all applied mutations).
    pub fn graph(&self) -> &Graph {
        &self.working
    }

    /// The accumulated patch.
    pub fn patch(&self) -> &Patch {
        &self.patch
    }

    /// The obligation set.
    pub fn obligations(&self) -> &ObligationSet {
        &self.obligations
    }

    /// Whether an entry has been examined during obligation discharge.
    pub fn is_visited(&self, id: &EntryId) -> bool {
        self.visited.contains(id)
    }

    // -- mutation ------------------------------------------------------------

    /// Apply a mutation to the working graph.
    ///
    /// Records the mutation in the patch. For entry-content mutations
    /// (`UpdateEntry`, `RemoveEntry`), generates obligations on all
    /// dependent entries. Fails if the mutation targets a locked entry.
    pub fn mutate(&mut self, mutation: Mutation) -> Result<(), SessionError> {
        // Check lock constraint for entry-content mutations.
        match &mutation {
            | Mutation::UpdateEntry { id, .. } | Mutation::RemoveEntry(id) => {
                if self.working.is_locked(id) {
                    return Err(SessionError::EntryLocked(id.clone()));
                }
            }
            | _ => {}
        }
        self.apply_and_propagate(mutation)
    }

    // -- obligation discharge ------------------------------------------------

    /// Confirm the obligation's target is still valid.
    ///
    /// Marks the obligation as discharged and adds the target to the
    /// visited set.
    pub fn confirm(&mut self, id: ObligationId) -> Result<(), SessionError> {
        let obligation = self
            .obligations
            .get(&id)
            .ok_or_else(|| SessionError::ObligationNotFound(id.clone()))?;
        if !matches!(obligation.status(), ObligationStatus::Pending) {
            return Err(SessionError::ObligationNotPending(id));
        }
        let target = obligation.target().clone();
        self.visited.insert(target);
        self.obligations.get_mut(&id).unwrap().set_status(ObligationStatus::Discharged);
        Ok(())
    }

    /// Discharge an obligation by updating the target entry.
    ///
    /// Applies the update through the normal `mutate()` path, which may
    /// generate further obligations on dependents. If the target entry is
    /// locked, `mutate()` returns `EntryLocked` — the agent should use
    /// `justify()` instead.
    pub fn resolve(&mut self, id: ObligationId, update: Mutation) -> Result<(), SessionError> {
        let obligation = self
            .obligations
            .get(&id)
            .ok_or_else(|| SessionError::ObligationNotFound(id.clone()))?;
        if !matches!(obligation.status(), ObligationStatus::Pending) {
            return Err(SessionError::ObligationNotPending(id));
        }
        let target = obligation.target().clone();
        self.mutate(update)?;
        self.visited.insert(target);
        self.obligations.get_mut(&id).unwrap().set_status(ObligationStatus::Discharged);
        Ok(())
    }

    /// Submit a justification for a locked entry's obligation.
    ///
    /// `argument_entry` must already exist in the working graph and carries the
    /// justification text. The obligation remains pending (as
    /// `AwaitingApproval`) until a reviewer calls `approve()`.
    pub fn justify(
        &mut self, id: ObligationId, argument_entry: EntryId, mutation: Mutation,
    ) -> Result<(), SessionError> {
        let obligation = self
            .obligations
            .get(&id)
            .ok_or_else(|| SessionError::ObligationNotFound(id.clone()))?;
        if !matches!(obligation.status(), ObligationStatus::Pending) {
            return Err(SessionError::ObligationNotPending(id));
        }
        if self.working.entry(&argument_entry).is_none() {
            return Err(GraphError::EntryNotFound(argument_entry).into());
        }
        let entry = obligation.target().clone();
        debug!(obligation = %id, target = %entry, argument_entry = %argument_entry, "submitted justification");
        let justification = Justification::new(entry, mutation, argument_entry);
        self.obligations
            .get_mut(&id)
            .unwrap()
            .set_status(ObligationStatus::AwaitingApproval(justification));
        Ok(())
    }

    /// Approve a pending justification (external reviewer action).
    ///
    /// Applies the deferred mutation directly — the approval is the
    /// authorization, so the lock is not rechecked. Generates further
    /// obligations on dependents and adds the target to the visited set.
    pub fn approve(&mut self, id: ObligationId) -> Result<(), SessionError> {
        let obligation = self
            .obligations
            .get(&id)
            .ok_or_else(|| SessionError::ObligationNotFound(id.clone()))?;
        let justification = match obligation.status() {
            | ObligationStatus::AwaitingApproval(j) => j.clone(),
            | _ => return Err(SessionError::ObligationNotAwaitingApproval(id)),
        };
        if self.working.entry(justification.argument_entry()).is_none() {
            return Err(GraphError::EntryNotFound(justification.argument_entry().clone()).into());
        }
        let target = obligation.target().clone();
        let argument_entry = justification.argument_entry().clone();
        // Apply the deferred mutation, bypassing lock check.
        self.apply_and_propagate(justification.into_mutation())?;
        self.visited.insert(target);
        debug!(obligation = %id, argument_entry = %argument_entry, "approved justification");
        self.obligations.get_mut(&id).unwrap().set_status(ObligationStatus::Discharged);
        Ok(())
    }

    // -- commit --------------------------------------------------------------

    /// Promote the patch to a new checkpoint. Consumes the session.
    ///
    /// A session commits only if the resulting graph is coherent under
    /// `validator`.
    pub fn commit<V: GroundingValidator>(self, validator: &V) -> Result<Checkpoint, SessionError> {
        if self.obligations.has_pending_approvals() {
            return Err(SessionError::ApprovalsIncomplete);
        }
        if !self.obligations.is_complete() {
            return Err(SessionError::ObligationsIncomplete);
        }
        self.working.validate_groundings(validator)?;
        Ok(Checkpoint::new(self.working))
    }

    // -- internal ------------------------------------------------------------

    /// Apply a mutation to the working graph, record it in the patch,
    /// and generate obligations on dependents for entry-content mutations.
    ///
    /// Does not check locks. Callers are responsible for lock enforcement.
    fn apply_and_propagate(&mut self, mutation: Mutation) -> Result<(), SessionError> {
        // Capture the cause entry and its dependents before applying.
        // RemoveEntry deletes edges, so dependents must be captured first.
        let cause_and_dependents: Option<(EntryId, Vec<EntryId>)> = match &mutation {
            | Mutation::UpdateEntry { id, .. } | Mutation::RemoveEntry(id) => {
                let dependents: Vec<EntryId> = self.working.dependents_of(id).cloned().collect();
                Some((id.clone(), dependents))
            }
            | _ => None,
        };

        // Apply mutation to the working graph.
        Self::apply_to_graph(&mut self.working, &mutation)?;

        // Record in the patch.
        self.patch.push(mutation);

        // Generate obligations on dependents.
        if let Some((cause, dependents)) = cause_and_dependents {
            for dependent in dependents {
                self.obligations.generate(dependent, cause.clone());
            }
        }

        Ok(())
    }

    /// Apply a single mutation to a graph.
    fn apply_to_graph(graph: &mut Graph, mutation: &Mutation) -> Result<(), GraphError> {
        match mutation {
            | Mutation::CreateEntry(entry) => {
                graph.insert_entry(entry.clone())?;
            }
            | Mutation::RemoveEntry(id) => {
                graph.remove_entry(id).ok_or_else(|| GraphError::EntryNotFound(id.clone()))?;
            }
            | Mutation::UpdateEntry { id, name, description, explanation } => {
                let entry =
                    graph.entry_mut(id).ok_or_else(|| GraphError::EntryNotFound(id.clone()))?;
                match name {
                    | FieldUpdate::Set(n) => entry.set_name(Some(n.clone())),
                    | FieldUpdate::Clear => entry.set_name(None),
                    | FieldUpdate::Unchanged => {}
                }
                match description {
                    | FieldUpdate::Set(d) => entry.set_description(d.clone()),
                    // Note: description is a required field; Clear is a no-op.
                    | FieldUpdate::Clear | FieldUpdate::Unchanged => {}
                }
                match explanation {
                    | FieldUpdate::Set(e) => entry.set_explanation(e.clone()),
                    // Note: explanation is a required field; Clear is a no-op.
                    | FieldUpdate::Clear | FieldUpdate::Unchanged => {}
                }
            }
            | Mutation::AddDependency(dep) => {
                graph.add_dependency(dep.clone())?;
            }
            | Mutation::RemoveDependency(dep) => {
                graph.remove_dependency(dep);
            }
            | Mutation::AddAffinity(aff) => {
                graph.add_affinity(aff.clone())?;
            }
            | Mutation::RemoveAffinity(aff) => {
                graph.remove_affinity(aff);
            }
            | Mutation::AddGrounding { entry, grounding } => {
                graph.add_grounding(entry, grounding.clone())?;
            }
            | Mutation::Lock(id) => {
                graph.lock(id)?;
            }
            | Mutation::Unlock(id) => {
                graph.unlock(id);
            }
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use std::fs;
    use std::time::{SystemTime, UNIX_EPOCH};

    use super::{Checkpoint, Session};
    use crate::edge::Dependency;
    use crate::entry::{Entry, EntryId};
    use crate::graph::Graph;
    use crate::grounding::{
        Grounding, GroundingValidationError, StructuralGroundingValidator, TelescopeAnchor,
        TelescopeGrounding,
    };
    use crate::mutation::{FieldUpdate, Mutation};
    use crate::obligation::ObligationStatus;
    use crate::repository::WorkspaceGroundingValidator;

    fn entry(id: &str) -> Entry {
        Entry::new(EntryId::new(id), format!("{id} description"), format!("{id} explanation"))
    }

    struct TempWorkspace {
        root: std::path::PathBuf,
    }

    impl TempWorkspace {
        fn new(name: &str) -> Self {
            let unique = SystemTime::now().duration_since(UNIX_EPOCH).unwrap().as_nanos();
            let root = std::env::temp_dir().join(format!("sirno-session-{name}-{unique}"));
            fs::create_dir_all(&root).unwrap();
            Self { root }
        }

        fn write(&self, relative: &str, contents: &str) {
            let path = self.root.join(relative);
            if let Some(parent) = path.parent() {
                fs::create_dir_all(parent).unwrap();
            }
            fs::write(path, contents).unwrap();
        }
    }

    impl Drop for TempWorkspace {
        fn drop(&mut self) {
            let _ = fs::remove_dir_all(&self.root);
        }
    }

    #[test]
    fn justification_points_at_an_entry() {
        let cause = EntryId::new("cause");
        let target = EntryId::new("target");
        let argument = EntryId::new("justify-target-update");

        let mut graph = Graph::new();
        graph.insert_entry(entry(cause.as_str())).unwrap();
        graph.insert_entry(entry(target.as_str())).unwrap();
        graph.insert_entry(entry(argument.as_str())).unwrap();
        graph.add_dependency(Dependency::new(cause.clone(), target.clone())).unwrap();
        graph.lock(&target).unwrap();

        let checkpoint = Checkpoint::new(graph);
        let mut session = Session::new(checkpoint);
        session
            .mutate(Mutation::UpdateEntry {
                id: cause.clone(),
                name: FieldUpdate::Unchanged,
                description: FieldUpdate::Set("updated cause".to_owned()),
                explanation: FieldUpdate::Unchanged,
            })
            .unwrap();

        let obligation = session.obligations().pending().next().unwrap().id().clone();
        session
            .justify(
                obligation.clone(),
                argument.clone(),
                Mutation::UpdateEntry {
                    id: target.clone(),
                    name: FieldUpdate::Unchanged,
                    description: FieldUpdate::Set("updated target".to_owned()),
                    explanation: FieldUpdate::Unchanged,
                },
            )
            .unwrap();

        match session.obligations().get(&obligation).unwrap().status() {
            | ObligationStatus::AwaitingApproval(justification) => {
                assert_eq!(justification.entry(), &target);
                assert_eq!(justification.argument_entry(), &argument);
            }
            | status => panic!("unexpected status: {status:?}"),
        }
    }

    #[test]
    fn commit_rejects_invalid_groundings() {
        let owner = EntryId::new("owner");
        let other = EntryId::new("other");

        let mut graph = Graph::new();
        graph.insert_entry(entry(owner.as_str())).unwrap();
        graph.insert_entry(entry(other.as_str())).unwrap();

        let checkpoint = Checkpoint::new(graph);
        let mut session = Session::new(checkpoint);
        session
            .mutate(Mutation::AddGrounding {
                entry: owner.clone(),
                grounding: Grounding::Telescope(TelescopeGrounding::new(TelescopeAnchor::new(
                    other.clone(),
                ))),
            })
            .unwrap();

        let error = session.commit(&StructuralGroundingValidator).unwrap_err();
        match error {
            | super::SessionError::GroundingInvalid(failure) => {
                assert_eq!(failure.entry(), &owner);
                assert_eq!(failure.grounding_index(), 0);
                assert_eq!(
                    failure.source(),
                    &GroundingValidationError::AnchorEntryMismatch {
                        entry: owner,
                        anchor_entry: other,
                    }
                );
            }
            | other => panic!("unexpected error: {other:?}"),
        }
    }

    #[test]
    fn commit_accepts_structurally_valid_groundings() {
        let owner = EntryId::new("owner");

        let mut graph = Graph::new();
        graph.insert_entry(entry(owner.as_str())).unwrap();

        let checkpoint = Checkpoint::new(graph);
        let mut session = Session::new(checkpoint);
        session
            .mutate(Mutation::AddGrounding {
                entry: owner.clone(),
                grounding: Grounding::Telescope(TelescopeGrounding::new(TelescopeAnchor::new(
                    owner.clone(),
                ))),
            })
            .unwrap();

        let checkpoint = session.commit(&StructuralGroundingValidator).unwrap();
        assert_eq!(checkpoint.graph().groundings(&owner).len(), 1);
    }

    #[test]
    fn commit_accepts_workspace_validated_telescope_groundings() {
        let workspace = TempWorkspace::new("workspace-commit");
        let owner = EntryId::new("owner");
        workspace.write("src/lib.rs", "// @sirno:owner\nfn anchored() {}\n");

        let mut graph = Graph::new();
        graph.insert_entry(entry(owner.as_str())).unwrap();

        let checkpoint = Checkpoint::new(graph);
        let mut session = Session::new(checkpoint);
        session
            .mutate(Mutation::AddGrounding {
                entry: owner.clone(),
                grounding: Grounding::Telescope(TelescopeGrounding::new(TelescopeAnchor::new(
                    owner.clone(),
                ))),
            })
            .unwrap();

        let validator = WorkspaceGroundingValidator::new(workspace.root.clone());
        let checkpoint = session.commit(&validator).unwrap();
        assert_eq!(checkpoint.graph().groundings(&owner).len(), 1);
    }
}
